[build]
builder = "NIXPACKS"
buildCommand = "CI=false npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
runtime = "LEGACY"
numReplicas = 1
startCommand = "npm run serve"
sleepApplication = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10